# Workflow to MANUALLY deploy a static website to an S3 bucket

name: Manual Deploy to S3

on:
  # THIS IS THE KEY CHANGE
  # This trigger allows you to run this workflow manually from the Actions tab in GitHub
  workflow_dispatch:

# Grant GITHUB_TOKEN the permissions required to fetch an OIDC token
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        # Checks out the code from the branch you select when you run the workflow
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Paste the ARN of the IAM role you created in AWS
          role-to-assume: arn:aws:iam::ACCOUNT_ID:role/YOUR_IAM_ROLE_NAME # ⚠️ CHANGE THIS
          aws-region: us-east-1 # ⚠️ CHANGE THIS to your bucket's region

      - name: Deploy static site to S3 bucket
        run: |
          aws s3 sync . s3://simberwebsite --delete
          echo "Deployment successful! Visit your site."
